<a href="https://colab.research.google.com/github/rijafatima8234/Numpy-Assignment/blob/main/Numpy_assingment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Name : Rija Fatima
# Roll no : 892370


In [ ]:
# Task 1
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

total = np.sum(numbers)
average = np.mean(numbers)
maximum = np.max(numbers)
minimum = np.min(numbers)

print("Array:", numbers)
print("Sum:", total)
print("Average:", average)
print("Maximum:", maximum)
print("Minimum:", minimum)

Array: [10 20 30 40 50]
Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10


In [ ]:
# Task 2
import numpy as np

numbers = np.array([45, 80, 30, 90, 55, 20])
result = numbers[numbers >= 50]

print("Values greater than or equal to 50:", result)

Values greater than or equal to 50: [80 90 55]


In [ ]:
# Task 3
import numpy as np
numbers = np.array([1, 2, 3, 4, 5, 6])

new_array = numbers.reshape(2, 3)

print(new_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Task 4
import numpy as np
marks = np.random.randint(40, 101, 10)

average = np.mean(marks)
highest = np.max(marks)
lowest = np.min(marks)

print("Random Marks:", marks)
print("Average Marks:", average)
print("Highest Marks:", highest)
print("Lowest Marks:", lowest)

Random Marks: [ 81  97  50  81  45  71  57  41 100  78]
Average Marks: 70.1
Highest Marks: 100
Lowest Marks: 41


In [ ]:
# Task 5
import numpy as np
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed_marks = marks[marks >= 50]
failed_marks = marks[marks < 50]

passed_students = np.sum(marks >= 50)
failed_students = np.sum(marks < 50)

print("Passed Marks:", passed_marks)
print("Failed Marks:", failed_marks)
print("Number of Passed Students:", passed_students)
print("Number of Failed Students:", failed_students)

Passed Marks: [67 89 90 70 58]
Failed Marks: [35 45 22]
Number of Passed Students: 5
Number of Failed Students: 3


In [ ]:
# All methods practice
# 1. Import NumPy

import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print("Array:", numbers)
print("Average:", np.mean(numbers))
print("Maximum:", np.max(numbers))

Array: [10 20 30 40 50]
Average: 30.0
Maximum: 50


In [ ]:
# 2. Python List vs NumPy Array
import numpy as np
marks = [70, 80, 90]

print("Python List:", marks)
marks_array = np.array([70, 80, 90])

print("NumPy Array:", marks_array)
print("After adding 5:", marks_array + 5)


mark_s = np.array([50, 60, 70, 80])
print(mark_s + 10)

Python List: [70, 80, 90]
NumPy Array: [70 80 90]
After adding 5: [75 85 95]
[60 70 80 90]


In [ ]:
# 3. Creating NumPy Arrays
import numpy as np
numbers = np.array([15, 25, 35, 45, 55])
print(numbers)

numbers = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])
print(numbers)

[15 25 35 45 55]
[[10 20]
 [30 40]
 [50 60]]


In [ ]:
# 4. Important Array Properties
import numpy as np

numbers = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60]
])
print("Dimensions:", numbers.ndim)
print("Shape:", numbers.shape)
print("Size:", numbers.size)
print("Data Type:", numbers.dtype)

Dimensions: 2
Shape: (3, 4)
Size: 12
Data Type: int64


In [ ]:
# 5. Indexing
import numpy as np
numbers = np.array([10, 20, 30, 40, 50])
print(numbers[1])
print(numbers[-1])
print(numbers[-2])

20
50
40


In [ ]:
# 6. Indexing in a 2D Array
import numpy as np

marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])
print("70:", marks[0, 0])
print("80:", marks[0, 1])
print("90:", marks[0, 2])
print("60:", marks[1, 0])
print("75:", marks[1, 1])
print("85:", marks[1, 2])

70: 70
80: 80
90: 90
60: 60
75: 75
85: 85


In [ ]:
# 7. Slicing
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print("Practice 1:", numbers[1:4])
print("Practice 2:", numbers[0:3])
print("Practice 3:", numbers[2:5])
print("Practice 4:", numbers[0:4])
print("Practice 5:", numbers[3:5])
print("Practice 6:", numbers[1:5])

Practice 1: [20 30 40]
Practice 2: [10 20 30]
Practice 3: [30 40 50]
Practice 4: [10 20 30 40]
Practice 5: [40 50]
Practice 6: [20 30 40 50]


In [ ]:
# 8. Vectorized Operations
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers + 5)
print(numbers * 2)
print(numbers - 5)
print(numbers / 5)
print(numbers ** 2)
print(numbers + 10)
print(numbers * 3)
print(numbers % 3)

[15 25 35 45 55]
[ 20  40  60  80 100]
[ 5 15 25 35 45]
[ 2.  4.  6.  8. 10.]
[ 100  400  900 1600 2500]
[20 30 40 50 60]
[ 30  60  90 120 150]
[1 2 0 1 2]


In [ ]:
# 9. Operations Between Two Arrays
import numpy as np

prices = np.array([100, 200, 300, 400])
discount = np.array([10, 20, 30, 40])

print(prices - discount)
print(prices + discount)
print(prices * discount)
print(prices / discount)

[ 90 180 270 360]
[110 220 330 440]
[ 1000  4000  9000 16000]
[10. 10. 10. 10.]


In [ ]:
# 10. Mathematical Functions
import numpy as np

numbers = np.array([36, 49, 64, 81])
print(np.sqrt(numbers))
print(np.power(numbers, 3))

numbers = np.array([-15, -8, 6, 12])
print(np.abs(numbers))

numbers = np.array([2.4, 5.6, 7.8, 9.3])
print(np.round(numbers))

[6. 7. 8. 9.]
[ 46656 117649 262144 531441]
[15  8  6 12]
[2. 6. 8. 9.]


In [ ]:
# 11. Aggregation Functions
import numpy as np

scores = np.array([45, 60, 75, 80, 90])

print(np.sum(scores))
print(np.mean(scores))
print(np.max(scores))
print(np.min(scores))
print(np.median(scores))
print(np.std(scores))

350
70.0
90
45
75.0
15.811388300841896


In [ ]:
import numpy as np

temperatures = np.array([25, 28, 30, 27, 32, 29])

print(np.sum(temperatures))
print(np.mean(temperatures))
print(np.max(temperatures))
print(np.min(temperatures))
print(np.median(temperatures))
print(np.std(temperatures))

171
28.5
32
25
28.5
2.217355782608345


In [ ]:
# 12. Conditions in NumPy
import numpy as np

marks = np.array([35, 50, 65, 80, 95])

print(marks > 50)
print(marks >= 50)
print(marks < 80)
print(marks <= 80)
print(marks == 65)
print(marks != 65)

[False False  True  True  True]
[False  True  True  True  True]
[ True  True  True False False]
[ True  True  True  True False]
[False False  True False False]
[ True  True False  True  True]


In [ ]:
# 13. Filtering Data
marks = np.array([42, 55, 68, 73, 39, 88, 95, 47])

passed = marks[marks >= 50]
print(passed)
failed = marks[marks < 50]
print(failed)
high_marks = marks[marks > 80]
print(high_marks)
average_marks = marks[(marks >= 50) & (marks <= 80)]
print(average_marks)

[55 68 73 88 95]
[42 39 47]
[88 95]
[55 68 73]


In [ ]:
# 14. Reshape
import numpy as np

numbers = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
new_array = numbers.reshape(3, 3)
print(new_array)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
# 15. Flatten
import numpy as np

marks = np.array([
    [70, 80, 90],
    [65, 75, 85]
])

flat_marks = marks.flatten()

print(flat_marks)

[70 80 90 65 75 85]


In [ ]:
# 16. Useful NumPy Functions
import numpy as np

print(np.zeros(8))
print(np.ones(6))
print(np.arange(5, 16))
print(np.arange(2, 21, 2))

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# 17. Random Numbers
import numpy as np

marks = np.random.randint(30, 101, 8)
print(marks)

numbers = np.random.randint(1, 51, 10)
print(numbers)

[62 99 62 72 95 91 81 67]
[24  4 46 31 21 21 18 20 17 28]
